server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${campus.datasource.driver-class-name}
      url: jdbc:mysql://${campus.datasource.host}:${campus.datasource.port}/${campus.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${campus.datasource.username}
      password: ${campus.datasource.password}
      validation-query: SELECT 1   # 用来检测连接是否有效的sql
      test-while-idle: true  # 如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      initial-size: 1  # 初始化时建立物理连接的个数
      min-idle: 1  # 即使超过空闲时间也不会被回收
      max-active: 8 # 最大连接数
      min-evictable-idle-time-millis: 300000 # 当空闲时间达到5分钟回收连接
      time-between-eviction-runs-millis: 60000 # 每过1分钟执行1次空闲检测

  redis:
    host: ${campus.data.redis.host}
    port: ${campus.data.redis.port}
    database: ${campus.data.redis.database}
    password: ${campus.data.redis.password}
    lettuce:
      pool:
        min-idle: 1
        max-active: 10
        max-idle: 5
        max-wait: -1ms


mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.campus.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: aslkdsajdlkjhdsfb
    user-ttl: 7200000
    user-token-name: authentication
  alioss:
    access-key-id: ${campus.alioss.access-key-id}
    access-key-secret: ${campus.alioss.access-key-secret}
    bucket-name: ${campus.alioss.bucket-name}
    endpoint: ${campus.alioss.endpoint}
    region: ${campus.alioss.region}
  wechat:
    appid: ${campus.wechat.appid}
    secret: ${campus.wechat.secret}
    mchid: ${campus.wechat.mchid}
    mch-serial-no: ${campus.wechat.mch-serial-no}
    private-key-file-path: ${campus.wechat.private-key-file-path}
    api-v3-key: ${campus.wechat.api-v3-key}
    we-chat-pay-cert-file-path: ${campus.wechat.private-key-file-path}
    notify-url: ${campus.wechat.notify-url}
    refund-notify-url: ${campus.wechat.refund-notify-url}
  baidu:
    ak: ${campus.baidu.ak}
    location-url: ${campus.baidu.location-url}
    distance-url: ${campus.baidu.distance-url}
  shop:
    location:
      lng: ${campus.shop.location.lng}
      lat: ${campus.shop.location.lat}
    limit-distance: ${campus.shop.limit-distance}